### ISSUE TITLE
Suggestion: Upload to Modrinth

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [soir20/MoreMcmeta#1]
**Is your feature request related to a problem? Please describe.**
Modrinth is a new mod platform which is similar to curseforge, but has a nice ui, is faster, more user-friendly and develoepr-friendly, is open source, etc.

**Describe the solution you'd like**
Uploading the mod to Modrinth.
 
**Describe alternatives you've considered**
N/A

**Which Minecraft versions would this feature apply to?**
Replace the space inside the brackets with an "x" to select a version.
- [x] 1.16
- [x] 1.17

**Comment by soir20** [comment]
Thanks for letting me know about Modrinth. I'll close this issue once I get a page set up for it.

**Comment by DragonEggBedrockBreaking** [comment]
Btw, you can set up a gradle plugin which automatically pushes builds to modrinth :-)

**Comment by soir20** [comment]
I saw the Gradle plugins for Modrinth (and CurseForge), though so far I haven't published builds often enough to justify the time to set them up. If publishing on both CF pages and a Modrinth page becomes annoying, I'll add them to the build script.

**Comment by soir20** [comment]
I've created the Modrinth page. I'll close this issue with a link once it is approved.

**Comment by wafflecoffee** [comment]
https://modrinth.com/mod/moremcmeta ;)
