### ISSUE TITLE
port to neoforge?

### ISSUE THREAD

**Issue by VaporeonScripts** [soir20/MoreMcmeta#100]
**Is your feature request related to a problem? Please describe.**
yes, my modpack cant be published due to continuity (fabric mod) used along connector, which works, but on curseforge i cant cuz its a fabric mod, and continuity is needed for a resource pack i use, so i cant find any neoforge alternatives.

**Describe the solution you'd like**
port to neoforge

**Describe alternatives you've considered**
nope sadly
**Which Minecraft versions would this feature apply to?**
1.21.1 neoforge

**Additional context**
.

**Comment by soir20** [comment]
There is an existing tracking issue open for this: #72. I will close this one as a duplicate in favor of the existing issue. I do plan to release to NeoForge, but it's a lot of work to set everything up for a third loader, so I haven't gotten to do this yet.
