### ISSUE TITLE
GlStateManager crash with Iris using some shader packs, + fix json to include 1.21.1 please

### ISSUE THREAD

**Issue by toastedfoxx** [soir20/MoreMcmeta#105]
**Describe the bug**
shaders are supposed to be 

**To reproduce**
start a world with the shaders and mcmeta, enable shaders

**Expected behavior**
shaders to work LOL

**Screenshots or videos**
![image](https://github.com/user-attachments/assets/6f6b0f31-3813-4e33-aa9a-4c5adea75986)

**Which Minecraft versions does this bug affect?**
1.21 possibly others

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [O] Fabric

**Mods list**
Advancement Frames
Almanac
Alternate Current
AmbientSounds
Amendments
Animal Feeding Trough
Another Furniture
AppleSkin
Architectury
Artifacts
Ash API
Aurelj's Vanilla Paintings
Axes Are Weapons
Balm
BedrockIfy
Better Advancements
Better Climbing
Better Statistics Screen
Better Third Person
Better Tridents
BetterF1
BetterThanMending
Blur+ (Fabric)
Bookshelf
Bundle Recipe
CICADA
CIT Resewn
Cardiac
Carry On
Chalk
Chalk: Colorful-Addon
Chat Heads
Chat Patches
Cherished Worlds
Clean F3
Clean Tooltips
Clear Despawn Reworked
Client Tweaks
Cloth Config v15
Clumps
Cobweb
Collective
Connectible Chains
Continuity
Controlling
Crawl
CreativeCore
Cristel Lib
Crying Portals
Cull Less Leaves
Cut Through
Cycle Paintings
Cycle Title Screen Splash
DEUF Refabricated
Dark Loading Screen
Darker Trials
Debugify
Ding
Dismount Entity
Double Doors
Dynamic FPS
EMI
EMI Enchanting
EMI Loot
Easy Anvils
Easy Magic
Easy Shulker Boxes
Eating Animation
Elytra Slot
Enhanced Block Entities
Entity Model Features
Entity Texture Features
EntityCulling
Every Compat
Exordium
Explorify
Fabric API
Fabric Language Kotlin
FallingTree
Farmer's Delight
FastQuit
Faux-Custom-Entity-Data
FerriteCore
Flourish
Forge Config API Port
Formations
Formations Nether
Fowl Play
Friends & Foes
Friends&Foes - Beekeeper Hut
Friends&Foes - Flowery Mooblooms
Fzzy Config
Gardens of the Dead
GlitchCore
Global Packs
Hearths
ImmediatelyFast
Indium
Interactic
Inventory Essentials
Inventory Profiles Next
Inventory Totem
Iris
Item Obliterator
Jade
Jade Addons
JamLib
Jankson
Keep My Soil Tilled
KleeSlabs
Konkrete
Krypton
LambDynamicLights
Leaves Be Gone
Let Me Despawn
Lithium
Load My F***ing Tags
Luna Slimes
M.R.U
Mace but 3D
Melody
MidnightLib
Mod Menu
Model Gap Fix
ModernFix
Monsters in the Closet
Moonlight Lib
More Culling
MoreMcmeta
Mouse Tweaks
Name Tag Tweaks
Necronomicon
NetherPortalFix
Netherite But Cheaper
No Chat Reports
No Hostiles Around Campfire
No Resource Pack Warnings
Noisium
Not Enough Recipe Book
NotEnoughAnimations
Nullscape
Nyf's Spiders
OctoLib
Particle Core
Particle Mimicry
Particle Rain
Particle Tweaks
Particular
Pick Up Notifier
Placeholder API
Presence Footsteps
Pumpkin Pie Delight
Puzzle
Puzzles Lib
Quad
Reacharound
Repurposed Structures
Repurposed Structures - Farmer's Delight Compat
Repurposed Structures - Friends & Foes Compat
Right Click Harvest
Scaffolding Drops Nearby
Searchables
SeasonHUD
SereneSeasons
Show Me Your Skin!
Simple Copper Pipes
Simple Menu
Sodium
Sodium Extra
Sodium Shadowy Path Blocks
Sooty Chimneys
Soul Fire'd
Sound Physics Remastered
Sounds
Status Effect Bars
Structure Essentials Mod
Superflat World No Slimes
Supplementaries
Supplementaries
TCD Commons API
TerraBlender
Thorny Bush Protection
Tidal Towns
Title Fixer
Towns and Towers
Trailier Tales
Trinkets
Trowel
Universal Sawmill
Visual Workbench
Wakes
Waystones
Wilder Wild
Xaero's Minimap
Xaero's World Map
XaeroPlus
Xander's Sodium Options
YUNG's API
YUNG's Better Desert Temples
YUNG's Better Dungeons
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Bridges
YUNG's Extras
YetAnotherConfigLib
You've Goat to be kidding me
Zoomify
biomemusic mod
cupboard
essential-container
iChunUtil
leaky Mod
libIPN
oωo
recipeessentials Mod

**Resource pack**
![image](https://github.com/user-attachments/assets/09d4dfb6-e6ed-4b87-b884-aeee986d7fa4)

**Additional context**
[Add any other context about the problem here.](https://github.com/MoreMcmeta/core/blob/5094bdf9895da2f33597127ecd0774d8c615454b/common/src/main/java/io/github/moremcmeta/moremcmeta/impl/client/texture/BoundTextureState.java#L41) fix this line

**Comment by soir20** [comment]
To be clear, that line you linked is not saying only 12 textures can exist in the game. It's saying there can be a maximum of 12 texture units that are simultaneously bound in OpenGL. Vanilla Minecraft's `GlStateManager` uses the same array capacity, and clearly more than 12 textures exist.

**Comment by soir20** [comment]
I'd also like to see the full stack trace--I had tested this with Iris and did not see this exception.

**Comment by soir20** [comment]
In any event, it's an easy fix for MoreMcmeta to not crash when there are more than 12 texture units that need to be bound simultaneously. However, I just tested the new 4.5.0 version with MoreMcmeta + MoreMcmeta emissive + Sodium + Iris and a shader pack, and it did not crash. So this issue seems specific to your shader pack or some other mod you are using.

**Comment by toastedfoxx** [comment]
I can leave the full stack trace tomorrow

**Comment by toastedfoxx** [comment]
> In any event, it's an easy fix for MoreMcmeta to not crash when there are more than 12 texture units that need to be bound simultaneously. However, I just tested the new 4.5.0 version with MoreMcmeta + MoreMcmeta emissive + Sodium + Iris and a shader pack, and it did not crash. So this issue seems specific to your shader pack or some other mod you are using.


https://mclo.gs/7xF4uT7

**Comment by soir20** [comment]
Looks like an interaction between MoreMcmeta and Konkrete. However, the straightforward fix I mentioned still applies. It'll be part of the next release.

**Comment by toastedfoxx** [comment]
> Looks like an interaction between MoreMcmeta and Konkrete. However, the straightforward fix I mentioned still applies. It'll be part of the next release.

alright, thank you. i did try removing konkrete, but the same thing still happened 
https://mclo.gs/YIX988z , i will wait for the new release

**Comment by soir20** [comment]
MoreMcmeta 4.5.1 has been released. It adds bounds checks that should prevent the crash when mods need to bind textures beyond the 12 units supported in vanilla. Please note that the new version is still under review at CurseForge, though it should be approved in a few minutes, and it's already available on Modrinth.
