### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by Mafy-17** [soir20/MoreMcmeta#17]
1.19.3

Could you please update moremcmeta to 1.19,3 and thanks :)

**Comment by soir20** [comment]
Thanks for reporting. This is fixed on my end; I should be releasing a new version over the next few days. Mojang redid some portions of MC's resource loading code, which MoreMcmeta depends on, so I want to test this version upgrade a bit more than usual. Hopefully, I can get something out today, but we'll see.

**Comment by soir20** [comment]
1.19.3-3.0.5 (commit 64103d7e7dbb47b999f67cb26fc73bc027a290e7) has been released. It is currently under review at CurseForge. Please report any issues you encounter with the new version.
