### ISSUE TITLE
doesnt work for me plz help

### ISSUE THREAD

**Issue by yeete183** [soir20/MoreMcmeta#2]
it doesnt work i follow all steps here is my code 
{
    "animation": {
        "width": 64,
        "height": 640
    }
}
 and here is my textures 
![tabby2](https://user-images.githubusercontent.com/84253595/133063865-d6d73460-3a39-4166-8fc1-dfc0206b4452.png)

idk what i did wrong plz help
1.16 fabric

**Comment by yeete183** [comment]
its a blinkimg cat textuer fyi

**Comment by soir20** [comment]
The `height` parameter is for the height of an individual frame instead of the entire image. In this case, you need:
```
{
  "animation": {
    "width": 64,
    "height": 32
  }
}
```

**Comment by yeete183** [comment]
oh thank you :))

**Comment by yeete183** [comment]
wait does it work with optifine textures as well?

**Comment by yeete183** [comment]
still doesnt work?
![image](https://user-images.githubusercontent.com/84253595/133164911-66751c13-7c33-4d0d-9791-459aaff85ab2.png)
heres the files in my texture pack with that code u sent me and the cats still not blinking

**Comment by soir20** [comment]
First, please confirm that OptiFine is working by itself. If you add in a non-animated texture through the OptiFine system (like the first frame of your image without the .moremcmeta file), does OptiFine load it? I've heard that OptiFine and Fabric don't play well together. MoreMcmeta might be loading your texture correctly, but OptiFine isn't displaying it.

----

If OptiFine is working correctly, can you be more specific when you say that the cat is not blinking? Is your custom texture showing up in the game at all? Or, can you see the custom texture, but it isn't animating?

If your custom texture isn't showing up at all, you probably made a mistake in configuring the texture through OptiFine. It's also possible that the texture and its metadata are named incorrectly (the tabby2 part) or placed in the wrong folder, so OptiFine can't find it to display it on cats.

If it's just not animating, there may be an incompatibility between MoreMcmeta and OptiFine. However, I'd need the .zip file of your texture pack to be able to confirm that.

**Comment by yeete183** [comment]
optifine is displaying correctly but cat isnt blinking it just stuck on 1 frame the textures there but not animated
[mcmetatest.zip](https://github.com/soir20/MoreMcmeta/files/7157964/mcmetatest.zip)

**Comment by yeete183** [comment]
i can send a vid if that helps

**Comment by yeete183** [comment]
https://user-images.githubusercontent.com/84253595/133172797-225811b4-7f8a-4f5d-a883-c1df8bf9360e.mp4

heres a vid of the cat failing to blink

**Comment by soir20** [comment]
Can you confirm that you are running version 3.0.0 of MoreMcmeta? Versions below 3 do not support OptiFine animated textures.

If you are running version 3, please provide a full mod list, including your OptiFine version.

I had to move the texture/metadata inside the pack you provided into a cat directory within optifine/mobs, but other than that, I am seeing the cat blink on 1.16 Fabric with only MoreMcmeta 3, OptiFabric, and OptiFine installed.

**Comment by yeete183** [comment]
yes it is 3.0.0
heres my mod list 
![image](https://user-images.githubusercontent.com/84253595/133189224-62b9f3b8-3be9-4079-85dd-a960a36e0e33.png)
![image](https://user-images.githubusercontent.com/84253595/133189238-122fd461-a37d-4aea-92d7-30e6e3ae4a20.png)
some are my own mcreator mods

**Comment by soir20** [comment]
Nothing jumps out at me as being problematic, and I'm using the same OptiFine version. Can you move all of those mods except MoreMcmeta, OptiFine, and OptiFabric out of your mods folder, start a fresh world, and check if the blinking animation works?

Furthermore, do you know which of those mods adds the different cat model/tail animation you showed in the video? It's possible that whatever mod renders the custom models is using its own texturing and causing an incompatibility.

**Comment by yeete183** [comment]
ok its a texture pack under the mcmeta texture pack causing the tail animation

**Comment by yeete183** [comment]
nope still doesnt work

**Comment by yeete183** [comment]
the mcmeta pack is on the top fyi

**Comment by yeete183** [comment]
also its this textur epack that adds the cat tail https://www.curseforge.com/minecraft/texture-packs/animated-entities

**Comment by soir20** [comment]
In your resource pack, is the tabby2.png and .moremcmeta inside `MoreMCmeta/assets/minecraft/optifine/mob` or `MoreMCmeta/assets/minecraft/optifine/mob/cat`? If it's not in the `cat` subdirectory, please create one and move both files there.

Also, try moving your MoreMcmeta resource pack above Fabric resources and all other packs. I wonder if an identical but non-animated cat texture is in Fabric resources and overriding the animated one.

**Comment by yeete183** [comment]
oh h i just noticed thx hope it works

**Comment by yeete183** [comment]
ok it works now thx :)
