### ISSUE TITLE
NoClassDefError: com/mojang/bridge/game/GameVersion (Quilt)

### ISSUE THREAD

**Issue by sylv256** [soir20/MoreMcmeta#21]
**Describe the bug**
It tries to find `com/mojang/bridge/game/GameVersion` which does not exist.

**To reproduce**
1. Use the Library in a Quilt 1.19.4 dev env

**Which Minecraft versions does this bug affect?**
1.19.4

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [ ] Fabric
- [x] Quilt

**Log**
https://mclo.gs/QWPLY7S

**Mods list**
*See log*

**Additional context**
This happens in multiple Quilt 1.19.4 mod dev envs, so it can't be anything specific to my one mod. I don't see that class referenced anywhere in the bytecode nor in the source code, so I'm a little confused. I've honestly never seen anything like this before.

**Comment by soir20** [comment]
It's likely because of 1.19.4. Mojang updated some code that is related to `WorldVersion` (presumably `GameVersion` in your mappings), and one method that MoreMcmeta uses has been moved. I'm going to release a 1.19.4 version shortly. Can you verify whether that fixes the issue?

Thanks for reporting and including detailed logs.

**Comment by sylv256** [comment]
There doesn't appear to be a `GameVersion` at the specified package, which is why I'm rather confused. I'll see if the new update fixes it, though.

**Comment by sylv256** [comment]
Updating to the 1.19.4 version fixed the issue. Thanks!

**Comment by sylv256** [comment]
also, you might want to add a `loader: quilt` tag, since this is Quilt loader, not Fabric (although you may be right in that the issue might apply to fabric as well).

**Comment by soir20** [comment]
I used the Fabric tag since I don't currently develop a separate version for Quilt. Even if it's the Quilt loader, it's still the Fabric version of the mod.
