### ISSUE TITLE
up to 1.19.2

### ISSUE THREAD

**Issue by Pan-Etsu** [soir20/MoreMcmeta#22]
1.19.2

Could you please update moremcmeta to 1.19.3 ? :(

**Comment by soir20** [comment]
The latest 1.19 version (1.19-3.0.5) should work on 1.19.2. 3.0.6 versions only contain a small compatibility fix for a particular uncommon mod, so you should be fine to use 3.0.5.

[Link to Forge version](https://www.curseforge.com/minecraft/mc-mods/moremcmeta/files/3879265)
[Link to Fabric version](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-fabric/files/3879264)

Please reopen this issue if the 1.19 version does not work on 1.19.2.
