### ISSUE TITLE
Invalid resource names causing incompatibility with Continuity

### ISSUE THREAD

**Issue by DeadbushCarrot** [soir20/MoreMcmeta#24]
**Describe the bug**
Loading some resourcepacks will softlocks the game even if it doesn't even use the mod.

**To reproduce**
1. Go to 'Modrinth download Classic Improvements or use the link lower down'
2. Download Classic Improvements'
3. Add the resourcepack to the game'
4. Use the 'resourcepack'
5. Game softlocks

**Expected behavior**
Expected the game to load with no problems.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Which Minecraft versions does this bug affect?**
1.20.1.

**Mod loader**
Which mod loaders does this bug affect?
- [] Forge Didn't test 
- [] Fabric tested

**Mods list**
A lot but all are vanilla Mods used are from Fisal which is on Modrinth

**Resource pack**
Classic Improvements and Build in ones from Mods | Pack link https://modrinth.com/resourcepack/classicimprovements

**Additional context**
Classic Improvements is the only one I know that has this issue but other packs may have it too

**Comment by soir20** [comment]
Would you upload a log file from a session where this issue occurs? I'm unable to reproduce this with the resource pack you linked on Fabric 1.20.1. It's possible that this is an incompatibility with another mod and not an issue with specific resource packs.

**Comment by DeadbushCarrot** [comment]
> Would you upload a log file from a session where this issue occurs? I'm unable to reproduce this with the resource pack you linked on Fabric 1.20.1. It's possible that this is an incompatibility with another mod and not an issue with specific resource packs.

I did have Classic Improvements Add-on 1 loaded above Classic Improvements but it never crashed with just Add-on 1 but am did just redownload every mod to make sure all the mods are up to date but Ill get the log very soon

**Comment by DeadbushCarrot** [comment]
Ok here 
[latest.log](https://github.com/MoreMcmeta/core/files/11994651/latest.log)

**Comment by soir20** [comment]
I checked with the Classic Improvements Add-on 1 pack, but I'm still unable to reproduce this issue. There is nothing in your log file to indicate that MoreMcmeta failed while it was attempting to load these resource packs. This definitely sounds like an incompatibility with another mod.

Can you try removing mods to see which are causing the incompatibility? (Remove half of your mods besides MoreMcmeta, see if it still happens, and keep removing half to narrow it down until you can find which one is incompatible.)

Furthermore, it looks like there are some redundant mods in your list. MoreMcmeta and Animatica will both try to load OptiFine animated textures. If you have emissive textures enabled for Continuity, both MoreMcmeta and Continuity will try to load OptiFine emissive block textures. I'm not sure if that's the cause of this issue, but it might lead to other problems when you try to use those features later on.

**Comment by DeadbushCarrot** [comment]
Ok I only have Continuity, sodium and moremcmeta and it will just fail to load the pack it wont softlock and yes I have Indium

**Comment by DeadbushCarrot** [comment]
> I checked with the Classic Improvements Add-on 1 pack, but I'm still unable to reproduce this issue. There is nothing in your log file to indicate that MoreMcmeta failed while it was attempting to load these resource packs. This definitely sounds like an incompatibility with another mod.
> 
> Can you try removing mods to see which are causing the incompatibility? (Remove half of your mods besides MoreMcmeta, see if it still happens, and keep removing half to narrow it down until you can find which one is incompatible.)
> 
> Furthermore, it looks like there are some redundant mods in your list. MoreMcmeta and Animatica will both try to load OptiFine animated textures. If you have emissive textures enabled for Continuity, both MoreMcmeta and Continuity will try to load OptiFine emissive block textures. I'm not sure if that's the cause of this issue, but it might lead to other problems when you try to use those features later on.

Ok I only have Continuity, sodium and moremcmeta and it will just fail to load the pack it wont softlock and yes I have Indium

**Comment by soir20** [comment]
It looks like you have a file that is improperly named:
```
Non [a-z0-9/._-] character in path of location: minecraft:optifine/ctm/tinted_glass/old tinted glass back up/27.png
```

Minecraft files are not allowed to have spaces in their names, only hyphens and underscores.

This is something that MoreMcmeta should handle better, so I'll release a fix for it. You can resolve the issue for the time being by removing files with spaces from your resource pack.

(Continuity is requesting this file from MoreMcmeta, which is why I couldn't reproduce it with just MoreMcmeta.)

**Comment by DeadbushCarrot** [comment]
> It looks like you have a file that is improperly named:
> 
> ```
> Non [a-z0-9/._-] character in path of location: minecraft:optifine/ctm/tinted_glass/old tinted glass back up/27.png
> ```
> 
> Minecraft files are not allowed to have spaces in their names, only hyphens and underscores.
> 
> This is something that MoreMcmeta should handle better, so I'll release a fix for it. You can resolve the issue for the time being by removing files with spaces from your resource pack.
> 
> (Continuity is requesting this file from MoreMcmeta, which is why I couldn't reproduce it with just MoreMcmeta.)

well that folder isn't even meant be in use, weird its just a backup
EDIT I did find a tinted_glass.properties in the back up but it didn't fix it
ANOTHER EDIT It is continuity I have all my mods now expect continuity and it works

**Comment by soir20** [comment]
Version 4.0.1, which adds a check to handle resources with invalid names correctly in this case, has been released. It may take a few minutes for the files to be approved on CurseForge.

I'm not sure why Continuity is creating a path to this resource. Minecraft will normally not allow you to create locations (in code) to improperly-named files like this... it seems like they're bypassing those checks. However, any mod that does this shouldn't cause pack loading issues with MoreMcmeta going forward.
