### ISSUE TITLE
Nested default plugins incompatible with Quilt dev env

### ISSUE THREAD

**Issue by Oliver-makes-code** [soir20/MoreMcmeta#25]
**Describe the bug**
Same as #23, but actually this time
I am using .moremcmeta instead of .mcmeta

**Which Minecraft versions does this bug affect?**
1.20+

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [x] Fabric

Haven't tested forge

**Resource pack**
[repro.zip](https://github.com/MoreMcmeta/core/files/12035015/repro.zip)

**Comment by soir20** [comment]
I'm unable to reproduce this on Fabric 1.20. Would you upload logs from a game session where the issue occurred, and are you using any other mods?

**Comment by Oliver-makes-code** [comment]
Here's a log from my dev env: https://mclo.gs/hl95g62
It might be an issue with Quilt if you can't reproduce on fabric

**Comment by soir20** [comment]
Thanks for providing logs.

> [21:52:09] [Render thread/INFO] (MoreMcmeta) Loading 0 MoreMcmeta plugins:

MoreMcmeta 4.x is divided into multiple plugins/mods that are bundled together with Architectury/Fabric Loom. It looks like Quilt isn't handling nested mods correctly.

I'm willing to look into a workaround. However, Quilt isn't an officially supported by MoreMcmeta, and it's a lot of work for me to support/test Quilt in addition to Fabric and Forge. In the worst case, you could individually download the default plugins.

**Comment by soir20** [comment]
I just tested MoreMcmeta 4.0.1 on Quilt, and it looks like those plugins are loading correctly. Since your logs are from a dev env, I'm curious if it's only happening there. Do you have a public repository where I can look at the Gradle configuration of your mod?

For reference, Quilt should be loading 5 MoreMcmeta-related mods:
```
|     4 | MoreMcmeta                          | moremcmeta                          | 1.20.1-4.0.1      | Fabric  | bf465ccee09685156424228430df9c4efc57b9da | <mods>\moremcmeta-1.20.1-4.0.1-fabric.jar                                                           |                                                                        |
|     2 | MoreMcmeta Animation Plugin         | moremcmeta_animation_plugin         | 1.20.1-1.0.0      | Fabric  | bf465ccee09685156424228430df9c4efc57b9da | <mods>\moremcmeta-1.20.1-4.0.1-fabric.jar                                                           | /META-INF/jars/animation-plugin-fabric-1.20.1-1.0.0-fabric.jar         |
|     0 | MoreMcmeta JSON Parser Plugin       | moremcmeta_json_parser_plugin       | 1.20.1-1.0.1      | Fabric  | bf465ccee09685156424228430df9c4efc57b9da | <mods>\moremcmeta-1.20.1-4.0.1-fabric.jar                                                           | /META-INF/jars/json-parser-plugin-fabric-1.20.1-1.0.1-fabric.jar       |
|     6 | MoreMcmeta Properties Parser Plugin | moremcmeta_properties_parser_plugin | 1.20.1-1.0.1      | Fabric  | bf465ccee09685156424228430df9c4efc57b9da | <mods>\moremcmeta-1.20.1-4.0.1-fabric.jar                                                           | /META-INF/jars/properties-parser-plugin-fabric-1.20.1-1.0.1-fabric.jar |
|     1 | MoreMcmeta Texture Plugin           | moremcmeta_texture_plugin           | 1.20.1-1.0.0      | Fabric  | bf465ccee09685156424228430df9c4efc57b9da | <mods>\moremcmeta-1.20.1-4.0.1-fabric.jar                                                           | /META-INF/jars/texture-plugin-fabric-1.20.1-1.0.0-fabric.jar           |
```

**Comment by Oliver-makes-code** [comment]
Yeah I have a repository:
https://github.com/Sweet-Berry-Collective/Wandering-Wizardry
I'm pulling it in through Modrinth maven

**Comment by Oliver-makes-code** [comment]
It might be because Quilt Loader doesn't load JiJ'd mods inside dev

**Comment by soir20** [comment]
That seems like it's the issue. Is there a tracking issue that we can link this issue to, in case other people encounter the same problem? Or does Quilt not intend to fix it?

You can still use MoreMcmeta in a Quilt dev environment, but you'll need to include the default plugins manually. These plugins are published to the MoreMcmeta organization's GitHub Packages repository (along with "core"). There is example configuration available in the [plugin docs](https://github.com/MoreMcmeta/core/wiki/Plugin-Docs:-Maven). Even though you aren't developing a plugin, all MoreMcmeta packages are in this repository, so you just need to add config to pull in the four default plugins.

The [core build.gradle](https://github.com/MoreMcmeta/core/blob/575764cfe479fa103558a524e5d004c438287bd0/build.gradle#L71-L74) shows how to include the plugins in a dev environment. (You don't want to `include` them in your final build, though.)

**Comment by Oliver-makes-code** [comment]
I think this is intended behaviour on Quilt's part, considering QuiltMC/quilt-loader#107, thanks anyways!
