### ISSUE TITLE
Log spam with certain resourcepacks, which can potentially get excessive

### ISSUE THREAD

**Issue by SplendidAlakey** [soir20/MoreMcmeta#26]
**Describe the bug**

When using certain texture packs with MoreMcmeta, the logs get filled with potentially thousands of errors, relating to `Invalid metadata in file`.

**To reproduce**

1. Install the mod and either one of these packs: [Visual Shulker Labels](https://www.curseforge.com/minecraft/texture-packs/visual-shulker-labels) (warning: this one will cause excessive spam!) or [Animated Colored Axolotl](https://www.curseforge.com/minecraft/texture-packs/animated-colored-axolotl) (this one will only print a few error lines)
2. Make sure the pack is enabled and just check your latest.log

**Expected behavior**

Suppress the errors by default and only print it in dev, maybe? Or introduce a config option to disable such logging.

**Screenshots or videos**

-

**Which Minecraft versions does this bug affect?**

1.19.2

**Mod loader**

- [❔] Forge
- [✅] Fabric

**Mods list**

No other mods, just FAPI.

**Resource pack**

[Visual Shulker Labels](https://www.curseforge.com/minecraft/texture-packs/visual-shulker-labels) or [Animated Colored Axolotl](https://www.curseforge.com/minecraft/texture-packs/animated-colored-axolotl)

**Additional context**

The issue only occurs on MoreMcmeta 4.0.1. Rolling back to 3.0.5 removes the log spam.

Logs: https://gist.github.com/SplendidAlakey/969f0fd096563401e50092c7c499b2d4

**Comment by soir20** [comment]
These specific log messages are redundant and definitely something that can be reduced.

Theoretically, there can be log spam when a resource pack includes a lot of broken textures or metadata. Removing or reducing those types of logs can make it more difficult for me and for resource pack authors to debug issues. In those cases, I'm inclined to say that the resource pack author just needs to clean up the pack... it's rare for a pack to be _that_ broken.

Hence, I'll start working on a fix to reduce these "not yet implemented" log messages, but other types of MoreMcmeta messages won't be affected.

**Comment by SplendidAlakey** [comment]
My thinking was that these packs are not necessarily broken, but rather they were not aiming to utilize any MoreMcmeta features to begin with. In such cases, logging is kind of irrelevant, as they would likely not be interested in "fixing" the issue. Regardless, your solution should address exactly that.

**Comment by soir20** [comment]
I have a working fix. I'll be doing some more testing tomorrow, so a release should be coming within the next day or two.

**Comment by soir20** [comment]
MoreMcmeta v4.1.0 has been released. It may take a few minutes for the files to appear on CurseForge. Thanks for reporting!
