### ISSUE TITLE
OptiFine features

### ISSUE THREAD

**Issue by Madis0** [soir20/MoreMcmeta#27]
**Is your documentation request related to a problem? Please describe.**
The listing says
> Version 4.0.0 includes support for the .moremcmeta format (JSON) and the .properties format (from OptiFine).

but I'm not fully sure what it means.

**Describe the solution you'd like**
Explain what OptiFine features are supported, how do they differ from [Animatica](https://www.curseforge.com/minecraft/mc-mods/animatica/), [ETF](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric) and vanilla features (what isn't possible and had to be added?)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by soir20** [comment]
Thanks for reporting this; that intro paragraph has gotten a bit convoluted with all the updates.

I've drafted a rewritten intro below. Is this clearer? Do you have suggestions for how to improve it?

(I generally prefer not to make explicit comparisons with other mods in the intro paragraph. I feel like it can easily cross the line into criticizing other people's work.)

# Old intro
You can animate almost any texture in the game, including armor, mob, and GUI textures. Textures from other mods that use Minecraft's default texturing process work as well. As of version 3.0.0, you can synchronize any animation to the world's current day time with the `daytimeSync` parameter. Version 4.0.0 adds support for the `smoothAlpha` parameter, which adds smooth transitions between frames of differing transparency.

The [Animation Format Guide](https://github.com/MoreMcmeta/core/wiki/User-Docs:-Animation-Format) has a full list of textures and explains all of the parameters MoreMcmeta supports in detail.

MoreMcmeta is a client-sided mod, so you don't need to install it on a server.

# New intro
With MoreMcmeta, you can animate almost any texture with OptiFine `.properties` files or JSON `.moremcmeta` files. MoreMcmeta also adds support for new animation options, like daytime synchronization.

| Feature                                                                 | Vanilla                         | MoreMcmeta                                                                                 |
|-------------------------------------------------------------------------|---------------------------------|--------------------------------------------------------------------------------------------|
| Animated block textures                                                 | :heavy_check_mark:              | :heavy_check_mark:                                                                         |
| Animated entity and armor textures                                      | :x:                             | :heavy_check_mark:                                                                         |
| Animated sun and moon textures                                          | :x:                             | :heavy_check_mark:                                                                         |
| Animated map backgrounds                                                | :x:                             | :heavy_check_mark:                                                                         |
| OptiFine `.properties` animation files                                  | :x:                             | :heavy_check_mark:                                                                         |
| JSON animation files                                                    | `.mcmeta` files for blocks only | `.moremcmeta` files for any texture                                                        |
| Daytime synchronization for animations                                  | :x:                             | :heavy_check_mark:, with the `daytimeSync` parameter                                       |
| Smooth transitions between animation frames with different transparency | :x:                             | :heavy_check_mark:, with the `smoothAlpha` parameter                                       |
| Emissive textures                                                       | :x:                             | [Emissive Plugin](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-emissive-fabric) |

The [Animation Format Guide](https://github.com/MoreMcmeta/core/wiki/User-Docs:-Animation-Format) has a full list of textures and explains all of the parameters MoreMcmeta supports in detail.

MoreMcmeta is a client-sided mod, so you don't need to install it on a server.

**Comment by Madis0** [comment]
Hmm, so what I understand this mod supports _all_ kinds of animations and _all_ kinds of emissive textures equivalent to OptiFine format, plus own new features. But no other OptiFine features. Is that correct?

**Comment by soir20** [comment]
Yes, that's right.

From a dev perspective, MoreMcmeta's texture configuration API would make it easier to implement some of those features. However, I'm not aware of any mods that use MoreMcmeta to implement them currently.

**Comment by Madis0** [comment]
Got it. The new documentation page LGTM.

**Comment by soir20** [comment]
I've updated the mod pages on CurseForge and Modrinth, so I will close this issue.
