### ISSUE TITLE
[info] ongoing development despite mojangs mcmeta addition?

### ISSUE THREAD

**Issue by DadoIrie** [soir20/MoreMcmeta#28]
First and foremost sorry about posting this here, but since MoreMcMeta has no dedicated messaging platform like Discord, etc and my question depends on the future development of a resourcepack I had to ask here on Github.

Planning on using MoreMcmeta on a resourcepack and I'm curious if the mod is getting future updates beyond 1.20.1 despite Minecraft 1.20.2 resourcepack update regarding animations & mcmeta?

**Comment by soir20** [comment]
There are no plans to halt development. I think the wording in [snapshot news article](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w31a) is misleading:

> Any sprite can now be animated using .mcmeta files, similar to other atlases

This only refers to GUI textures, not all textures in the game. MoreMcmeta would still add support for animated entity textures, animated sun and moon textures, new parameters like `daytimeSync`, and OptiFine `.properties` files.

It's possible that, in time, vanilla animations could progress enough that it wouldn't make sense to maintain the animation part of MoreMcmeta anymore. I don't envision that happening anytime soon, though.

Even if the animation features of MoreMcmeta stopped being maintained in the far future, that doesn't prevent MoreMcmeta's configuration API (used by the emissive textures plugin) from being maintained. It'd be a one-line change to disable animations.

Please close this issue if this response answers your question.
