### ISSUE TITLE
Game crashes when Quilted Fabric API is present

### ISSUE THREAD

**Issue by bwilliance** [soir20/MoreMcmeta#33]
**Describe the bug**
When launching Minecraft with MoreMcmeta 4.2.1 and Quilted Fabric API, the game crashes.

**To reproduce**
1. Have both MoreMcmeta 4.2.1 and Quilted Fabric API 7.1.2 (both latest versions) in the mods folder
2. Run Minecraft
3. Game crashes
4. Error appears on Minecraft Launcher

**Expected behavior**
Game should run normally as it did using MoreMcmeta 4.2.0 (previous version)

**Screenshots or videos**
None

**Which Minecraft versions does this bug affect?**
1.20.1

**Mod loader**
Which mod loaders does this bug affect?
Quilt

**Mods list**
Mod Menu
Quilted Fabric API
MoreMcmeta

**Resource pack**
None

**Additional context**
I've read some of the other issues, and this issue might be related to #25, but judging by the replies, it seems that official Quilt support might not be much of a priority for this mod. However, the mod seemed to work fine fine for me on MoreMcmeta 4.2.0, the previous version. If Quilt support just isn't possible or if this is a Quilt issue, then that's understandable.

Here is the crash report:
[crash-2023-08-26_00.47.20-client.txt](https://github.com/MoreMcmeta/core/files/12444821/crash-2023-08-26_00.47.20-client.txt)

Error message on Minecraft Launcher:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "packs" is null
Exit Code: -1

**Comment by soir20** [comment]
Thanks for reporting. This appears to be a bug on Quilt's end, but there's also an improvement to MoreMcmeta's implementation that should avoid it. So I will release a fix version for MoreMcmeta and create an issue or PR for Quilt.

**Comment by soir20** [comment]
MoreMcmeta v4.2.2, which contains a fix for this issue, has been released. It will take a few minutes for approvals on CurseForge.

I will be making a PR to Quilt with a fix for the issue on their end, but you shouldn't experience the crash anymore (with or without the Quilt bug) on 4.2.2.
