### ISSUE TITLE
1.20.1-neoforge-47.1.76 - crash on startup

### ISSUE THREAD

**Issue by spunchbop121** [soir20/MoreMcmeta#36]
https://pastebin.com/bqc48ypq crash report
https://pastebin.com/eF6GmuDb latest log

**Comment by soir20** [comment]
This looks like a compatibility issue, though unfortunately the logs aren't super descriptive in this case. Can you narrow down your mods list by half until you can find the one that's causing the issue with MoreMcmeta?

**Comment by spunchbop121** [comment]
> This looks like a compatibility issue, though unfortunately the logs aren't super descriptive in this case. Can you narrow down your mods list by half until you can find the one that's causing the issue with MoreMcmeta?

emissive-plugin-1.20.1-1.1.1-forge.jar
moonlight-1.20-2.8.16-forge.jar
moremcmeta-1.20.1-4.2.2-forge.jar
supplementaries-1.20-2.5.26.jar

https://pastebin.com/dch8nFZ1
https://pastebin.com/bvY5YZ5C

**Comment by soir20** [comment]
Thanks for narrowing this down. This is a known issue with Moonlight; I submitted fixes to them earlier today: #35. I'll close this as a duplicate.

**Comment by soir20** [comment]
I also forgot to mention that you can downgrade to MoreMcmeta 4.1.0 as a workaround until Moonlight fixes this on their end.
