### ISSUE TITLE
Enchant Glint Blur

### ISSUE THREAD

**Issue by owenleonardd** [soir20/MoreMcmeta#40]
I am trying to get my enchant glint to not be blurred. I have both the core mod along with this plugin, and I've tried making the enchant glint not blurry, but it still renders blurry. My pack works perfectly with regular optifine, but with this mod, it doesnt work (I changed the file to a .moremcmeta)

**Comment by soir20** [comment]
Did you install the texture plugin separately? MoreMcmeta release versions include the texture plugin so that you don't need to add it. It's possible that including it twice caused it to be disabled.

**Comment by owenleonardd** [comment]
I originally tried it without the plugin and it didn't work. Is it possible that you could check if the enchant glint blur works properly for you? Just to see if its a problem with the pack I'm using as opposed to a bug with the mod?

**Comment by soir20** [comment]
I can check it, but definitely do not install any of these default plugins that are only on GitHub. I am going to transfer this issue to the core repo since that's the main issue tracker. (These plugin ones are mainly for internal technical things.)

**Comment by soir20** [comment]
MoreMcmeta v4.2.4, which contains a fix for this issue, has been released. It will take a few minutes for the release scripts to run and for CurseForge to approve the files. Thanks for reporting; please report any new issues you encounter.
