### ISSUE TITLE
item duplicate

### ISSUE THREAD

**Issue by LaithAlshakhs** [soir20/MoreMcmeta#42]
When wearing any armor and esc from the world and rejoining one of the armor pieces gets duplicated

Video:
https://github.com/MoreMcmeta/core/assets/94724743/8bf0a329-3654-42d7-9f8f-e35aca6b5c67

Minecraft versions:
1.19.2
1.20.1

Mod loader
-Fabric

Mods list
Modern industrialization

**Comment by soir20** [comment]
MoreMcmeta doesn't touch the inventory system at all, so I don't think this issue would be coming from MoreMcmeta. Can you verify that this happens without Modern Industrialization and any other mods?

**Comment by LaithAlshakhs** [comment]
> MoreMcmeta doesn't touch the inventory system at all, so I don't think this issue would be coming from MoreMcmeta. Can you verify that this happens without Modern Industrialization and any other mods?

Sure. This is without any mod.
https://github.com/MoreMcmeta/core/assets/94724743/bcc890d3-89a2-48e9-ab09-7a211df118b2

**Comment by soir20** [comment]
It looks like Modern Industrialization is still present in this video. Did you mean to report this issue to [Modern Industrialization](https://github.com/AztechMC/Modern-Industrialization/issues) instead of MoreMcmeta?

**Comment by LaithAlshakhs** [comment]
Sorry, but it isn’t there. You can look there is no item group for it

**Comment by soir20** [comment]
My bad, I must have clicked on the wrong link or tab. I can't reproduce this in my dev environment on 1.20.1. I'll check regular Minecraft. Can you check whether this happens without any mods, just Fabric? This seems like a very strange issue for it to be caused by MoreMcmeta.

**Comment by soir20** [comment]
I cannot reproduce this with Fabric Loader 0.14.21 and MoreMcmeta 4.2.4 on MC 1.20.1 and 1.19.2.

**Comment by LaithAlshakhs** [comment]
Sorry I didn't tell you before the version of fabric loader was 0.14.22 and MoreMcmeta 4.24

**Comment by soir20** [comment]
Can you confirm whether you still experience this issue when you remove all mods (including MoreMcmeta)? So the only thing you would have is Fabric loader (no Fabric API)

**Comment by LaithAlshakhs** [comment]
Yeah lol It's so weird sorry to put the problem on your mod
edit: I forgot to remove FAPI I'll try now

**Comment by LaithAlshakhs** [comment]
After more testing, I found that the problem came from vanilla Minecraft. Sorry for reporting without testing, and thank you.

**Comment by soir20** [comment]
No worries, thanks for confirming
