### ISSUE TITLE
Crash when reloading resources with F3 key 

### ISSUE THREAD

**Issue by spunchbop121** [soir20/MoreMcmeta#47]
crash report: https://pastebin.com/pSRcDcq4

1.20.1-Neoforge-47.1.76
Modlist:
emissive-plugin-1.20.1-2.0.0-forge.jar
moremcmeta-1.20.1-4.2.5-forge.jar

**Comment by soir20** [comment]
This is an issue with MoreMcmeta core, so I'll transfer this issue to that repository. I've released version 4.3.0, which should fix this issue. It will take a few minutes for the files to be approved by CurseForge. Thanks for reporting; please create an issue for any issues you encounter in the new version.
