### ISSUE TITLE
1.18 Port coming?

### ISSUE THREAD

**Issue by itsdinkd** [soir20/MoreMcmeta#5]
by chance?

**Comment by soir20** [comment]
Yup, there is a port coming. Issue #3 has been tricky to fix and is higher priority at the moment. (I've found an alternative working solution for that issue, so I'm hoping to get a 1.18 port out within a week or so once I finish cleaning that up.)

**Comment by itsdinkd** [comment]
Oh heck yeah. Thank you! Do your thing, just happy I came across this and
that it will be out for 1.18 xD will be a great addition to my modpack,
Another Quality modpack 2

**Comment by soir20** [comment]
A 1.18 version of MoreMcmeta, v.1.18.1-3.0.2, has been released on CurseForge for Forge and Fabric. I will be publishing the new version on GitHub and Modrinth later today.

v3.0.2 fixes a rare crash that could occur at world startup. This fix will be backported to 1.17 and 1.16 soon.
