### ISSUE TITLE
Can the "animation.frametime" property of .mcmeta be modified？

### ISSUE THREAD

**Issue by Koalemon** [soir20/MoreMcmeta#52]
I've done some dynamic PNGS, but the minimum unit of refresh rate is 1tick, which is a very low frequency for me.  I tried to modify them, but found it difficult.  I don't know if you've ever thought about doing this.  Maybe you can give me some guidance while I'm still trying to modify them.

**Comment by soir20** [comment]
Yes, you can modify the `frametime` property as specified in the [animation format guide](https://github.com/MoreMcmeta/core/wiki/User-Docs:-Animation-Format#property-definitions). Can you show what you've tried?

Keep in mind that the file extension needs to be `.moremcmeta` and not `.mcmeta`, and the property name is `frametime` and not `frameTime`.

**Comment by soir20** [comment]
There's also some examples in the [demo resource pack](https://www.curseforge.com/minecraft/texture-packs/moremcmeta-demo) (see `assets/minecraft/textures/entity/bat.png.moremcmeta`).

Also, I'm going to convert this to a discussion thread since it's more of a question.
