### ISSUE TITLE
Very long freezing or crash when loading big packs

### ISSUE THREAD

**Issue by magmamir** [soir20/MoreMcmeta#62]
**Describe the bug**
The game freezes or crashes when attempt to enable large packs, load the game with large packs, or click the "Resource Pack" button in settings with loaded large packs. This doesn't happen without this mod.

**To reproduce**
1. Install v1.20.2-4.4.5-fabric version of MoreMcmeta. I used Quilt loader, most likely will work with Fabric loader as well.
2. Download [this](https://www.curseforge.com/minecraft/texture-packs/monumenta-mmo-resource-pack/files/4961526) and [this](https://files.playmonumenta.com/resource-packs/MonumentaMusicPack.zip) resource packs
3. Try to enable these packs with loaded mod. You see enormously long loading or get crash. 
4. You can try enable them without mod, after which close Minecraft and load with mod. Loading (Mojang logo) will be extremely long. After the game loads you can try to click "Resource Pack" button in setting. You get extremely long freeze or crash.

**Comment by soir20** [comment]
Thanks for reporting. When you say the game crashes, is there a crash report generated so that it takes you back to the launcher screen? Or does your operating system close the game because it's frozen/not responding?

Furthermore, are you using any mods besides MoreMcmeta?

**Comment by magmamir** [comment]
Checked it out now. It seems that there is no crash report, and the game just closes because of no responding. My launcher also says that the game stopped due to lack of memory (it's not clear RAM or video memory). If it's important, i have allocated 8Gb RAM for Minecraft and GTX 1050 Ti with 4Gb of VRAM. I also tried to use [this version](https://modrinth.com/mod/animatica/version/0.6+1.20) of Animatica on the same Minecraft version and with the same settings and resource packs, and there were no freezes at all. 
If talking about mods, i found that this issue occurs whether i use MoreMcmeta in a modpack or with the Fabric API alone.

**Comment by soir20** [comment]
I've been able to reproduce this with both Quilt and Fabric, though it's not as severe on Fabric. It also seems less severe if I unzip the pack. That still isn't ideal, so I'll see if I can fix the issue in general.

**Comment by magmamir** [comment]
Thanks

**Comment by soir20** [comment]
I have a fix working locally so far. What's happening is that a previous fix to work around an issue with Quilt's standard libraries (#33) is interacting with a compatibility fix for mods that scan all resources (#59) in a way that makes Minecraft repeatedly scan every resource in the pack when the pack uses vanilla's .zip implementation.

I need to do further testing before a release. There will most likely be a release today or tomorrow if I do not find any new issues.

**Comment by soir20** [comment]
MoreMcmeta 4.4.6, which fixes this issue, has been released. It will take a few minutes for the files to be approved by CurseForge. Thanks for reporting; please report any issues you encounter with the new version.
