### ISSUE TITLE
Optifine animation file causes crash

### ISSUE THREAD

**Issue by AuracleTech** [soir20/MoreMcmeta#90]
`ender.properties` inside  `My Pack\assets\minecraft\optifine\anim\` causes a crash

The file contains

```env
x=119
y=159
w=98
h=98
to=textures/entity/chest/ender.png
from=textures/block/nether_portal.png
```

**Expected behavior**
Animation might be outdated, to verify, but I expected a warning, not crash

**Which Minecraft versions does this bug affect?**
1.21

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [x] Fabric

**Mods list**
![image](https://github.com/user-attachments/assets/ec39ca3b-9743-4f83-a0bf-5d06ee198bc8)

**Resource pack**
Its a mix of homemade files and existing packs files, a mix, legally cannot share

**Comment by soir20** [comment]
This issue is specific to animation files where the texture size is not a multiple of the frame size. It has been fixed in MoreMcmeta 4.5.0.
