### ISSUE TITLE
1.20.1 Log Spam

### ISSUE THREAD

**Issue by Krimatoria** [soir20/MoreMcmeta#96]
Forge 47.3.5
moremcmeta-1.20.1-4.4.7-forge.jar

![image](https://github.com/user-attachments/assets/889f9f10-5e52-4d22-a916-d1e3222669ed)
Of course, I'm glad that the mod says you don't have these mods. But this prevents you from viewing the log. Since I have 150 such messages. But I don't need these mods, although I'm glad that I found out about them thanks to such a notification, but it would be great if it were possible to remove these notifications from the log or convert them to the format of warnings, not errors. I don't have any installed: 

> 2636 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/lumium_powered_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2637 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/wood_detector_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2638 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/glinted_amethyst_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2639 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_extender/powered_powering.png (referenced by minecraft:optifine/emissive.properties)
> 2640 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/lead_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2641 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/amethyst_bricks.png (referenced by minecraft:optifine/emissive.properties)
> 2642 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_collector_active.png (referenced by minecraft:optifine/emissive.properties)
> 2643 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/powered_toggle_latch/powered_powering.png (referenced by minecraft:optifine/emissive.properties)
> 2644 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_sulfur_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2645 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/apatite_block.png (referenced by minecraft:optifine/emissive.properties)
> 2646 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/apatite_bricks.png (referenced by minecraft:optifine/emissive.properties)
> 2647 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/apatite_pillar_top.png (referenced by minecraft:optifine/emissive.properties)
> 2648 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/palettes/rose_quartz_side.png (referenced by minecraft:optifine/emissive.properties)
> 2649 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/ruby_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2650 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/apatite_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2651 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/powered_latch/powering.png (referenced by minecraft:optifine/emissive.properties)
> 2652 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/rose_quartz_block.png (referenced by minecraft:optifine/emissive.properties)
> 2653 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_composter_compost.png (referenced by minecraft:optifine/emissive.properties)
> 2654 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/smooth_amethyst.png (referenced by minecraft:optifine/emissive.properties)
> 2655 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/rose_quartz_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2656 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_repeater/item.png (referenced by minecraft:optifine/emissive.properties)
> 2657 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_nickel_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2658 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture cataclysm:textures/blocks/obsidian_explosion_trap_bricks_on.png (referenced by minecraft:optifine/emissive.properties)
> 2659 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/chiseled_allurite.png (referenced by minecraft:optifine/emissive.properties)
> 2660 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_soil_infuser_active.png (referenced by minecraft:optifine/emissive.properties)
> 2661 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/warped_anchor_top_powered.png (referenced by minecraft:optifine/emissive.properties)
> 2662 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/enderium_glass.png (referenced by minecraft:optifine/emissive.properties)
> 2663 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/prismarine_activator_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2664 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/warped_anchor_1.png (referenced by minecraft:optifine/emissive.properties)
> 2665 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture born_in_chaos_v1:textures/entities/pumpkinspiriti.png (referenced by minecraft:optifine/emissive.properties)
> 2666 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/allurite_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2667 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/lumium_detector_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2668 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture cataclysm:textures/blocks/purpur_void_rune_trap_block_on.png (referenced by minecraft:optifine/emissive.properties)
> 2669 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/lumium_activator_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2670 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/enderium_block.png (referenced by minecraft:optifine/emissive.properties)
> 2671 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/palettes/rose_quartz_top.png (referenced by minecraft:optifine/emissive.properties)
> 2672 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_composter_ready.png (referenced by minecraft:optifine/emissive.properties)
> 2673 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/copper_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2674 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_repeater/powered_powering.png (referenced by minecraft:optifine/emissive.properties)
> 2675 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_repeater/powered.png (referenced by minecraft:optifine/emissive.properties)
> 2676 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_silver_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2677 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/entity/sparkle/allurite_sparkle.png (referenced by minecraft:optifine/emissive.properties)
> 2678 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/large_rose_quartz_bud.png (referenced by minecraft:optifine/emissive.properties)
> 2679 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/powered_toggle_latch/powering.png (referenced by minecraft:optifine/emissive.properties)
> 2680 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_lead_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2681 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/prismarine_detector_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2682 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_cinnabar_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2683 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/prismarine_powered_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2684 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/glowflower.png (referenced by minecraft:optifine/emissive.properties)
> 2685 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/sapphire_block.png (referenced by minecraft:optifine/emissive.properties)
> 2686 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/deepslate_silver_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2687 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/warped_anchor_4.png (referenced by minecraft:optifine/emissive.properties)
> 2688 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/chiseled_amethyst.png (referenced by minecraft:optifine/emissive.properties)
> 2689 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/powered_latch/idle.png (referenced by minecraft:optifine/emissive.properties)
> 2690 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/ruby_block.png (referenced by minecraft:optifine/emissive.properties)
> 2691 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/enderium_glass_ctm.png (referenced by minecraft:optifine/emissive.properties)
> 2692 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/sulfur_ore_netherrack.png (referenced by minecraft:optifine/emissive.properties)
> 2693 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/palettes/small_rose_quartz_tiles.png (referenced by minecraft:optifine/emissive.properties)
> 2694 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/sulfur_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2695 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/wood_powered_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2696 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/glinted_lumiere_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2697 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/allurite_block.png (referenced by minecraft:optifine/emissive.properties)
> 2698 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_nullifier_active.png (referenced by minecraft:optifine/emissive.properties)
> 2699 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_soil_infuser_side_active.png (referenced by minecraft:optifine/emissive.properties)
> 2700 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/allurite_bricks.png (referenced by minecraft:optifine/emissive.properties)
> 2701 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_block.png (referenced by minecraft:optifine/emissive.properties)
> 2702 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lichen_cordyceps_bulb.png (referenced by minecraft:optifine/emissive.properties)
> 2703 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_collector_underlay.png (referenced by minecraft:optifine/emissive.properties)
> 2704 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/silver_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2705 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_bricks.png (referenced by minecraft:optifine/emissive.properties)
> 2706 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/charged_lumiere_block.png (referenced by minecraft:optifine/emissive.properties)
> 2707 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_sapphire_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2708 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_apatite_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2709 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/niter_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2710 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/apatite_pillar.png (referenced by minecraft:optifine/emissive.properties)
> 2711 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_extender/item.png (referenced by minecraft:optifine/emissive.properties)
> 2712 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/glow_ink_clumps.png (referenced by minecraft:optifine/emissive.properties)
> 2713 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/powered_toggle_latch/powered.png (referenced by minecraft:optifine/emissive.properties)
> 2714 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_niter_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2715 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture cataclysm:textures/blocks/void_lantern_block.png (referenced by minecraft:optifine/emissive.properties)
> 2716 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_potion_diffuser_active.png (referenced by minecraft:optifine/emissive.properties)
> 2717 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/warped_anchor_3.png (referenced by minecraft:optifine/emissive.properties)
> 2718 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture boh:textures/entities/unown.png (referenced by minecraft:optifine/emissive.properties)
> 2719 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture cataclysm:textures/blocks/void_stone.png (referenced by minecraft:optifine/emissive.properties)
> 2720 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_collector_top_active.png (referenced by minecraft:optifine/emissive.properties)
> 2721 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture born_in_chaos_v1:textures/entities/darkvortexn.png (referenced by minecraft:optifine/emissive.properties)
> 2722 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/zinc_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2723 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/controller_rail_powered.png (referenced by minecraft:optifine/emissive.properties)
> 2724 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_extender/powering.png (referenced by minecraft:optifine/emissive.properties)
> 2725 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/sapphire_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2726 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/aura_ringer_top_ringing.png (referenced by minecraft:optifine/emissive.properties)
> 2727 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/deepslate_zinc_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2728 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/amethyst_lamp.png (referenced by minecraft:optifine/emissive.properties)
> 2729 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/glinted_allurite_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2730 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_repeater/powering.png (referenced by minecraft:optifine/emissive.properties)
> 2731 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/entity/sparkle/sparkle.png (referenced by minecraft:optifine/emissive.properties)
> 2732 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/smooth_lumiere.png (referenced by minecraft:optifine/emissive.properties)
> 2733 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_tin_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2734 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/deepslate_ruby_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2735 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/palettes/rose_quartz_tiles.png (referenced by minecraft:optifine/emissive.properties)
> 2736 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/medium_rose_quartz_bud.png (referenced by minecraft:optifine/emissive.properties)
> 2737 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/chiseled_lumiere.png (referenced by minecraft:optifine/emissive.properties)
> 2738 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_lamp.png (referenced by minecraft:optifine/emissive.properties)
> 2739 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/lumiere_cluster.png (referenced by minecraft:optifine/emissive.properties)
> 2740 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/tin_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2741 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture create:textures/block/diodes/pulse_extender/powered.png (referenced by minecraft:optifine/emissive.properties)
> 2742 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture minecraft:textures/particle/sga.png (referenced by minecraft:optifine/emissive.properties)
> 2743 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/silver_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2744 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/cinnabar_block.png (referenced by minecraft:optifine/emissive.properties)
> 2745 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/devices/device_soil_infuser_top_active.png (referenced by minecraft:optifine/emissive.properties)
> 2746 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/aura_ringer_ringing.png (referenced by minecraft:optifine/emissive.properties)
> 2747 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture born_in_chaos_v1:textures/entities/lordofpumpkinss.png (referenced by minecraft:optifine/emissive.properties)
> 2748 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/wood_activator_rail_on.png (referenced by minecraft:optifine/emissive.properties)
> 2749 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/cinnabar_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2750 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/warped_anchor_2.png (referenced by minecraft:optifine/emissive.properties)
> 2751 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture thermal:textures/block/nickel_ore.png (referenced by minecraft:optifine/emissive.properties)
> 2752 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture supplementaries:textures/block/end_lamps/end_stone_lamp.png (referenced by minecraft:optifine/emissive.properties)
> 2753 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture biomesoplenty:textures/block/small_rose_quartz_bud.png (referenced by minecraft:optifine/emissive.properties)
> 2754 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/entity/sparkle/lumiere_sparkle.png (referenced by minecraft:optifine/emissive.properties)
> 2755 | [23:42:35] [Render thread/ERROR] [io.gi.mo.mo.im.cl.MoreMcmeta/]: Unable to find texture galosphere:textures/block/smooth_allurite.png (referenced by minecraft:optifine/emissive.properties)

**Comment by soir20** [comment]
@Krimatoria There's no need to close this as not planned unless you are no longer annoyed by the log spam. If I don't plan to take action, I will just close it myself. But I don't always get a chance to respond to all of these tickets or do a release immediately.

**Comment by soir20** [comment]
MoreMcmeta 4.5.0 lowers the severity of metadata and texture errors from `ERROR` to `WARN`. Thanks for reporting this; please report any QoL suggestions or other issues you may find in the future.
